dyniva_prompt_message.prompt_rule.*:
  type: config_entity
  label: 'Managed entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    type:
      type: string
      label: 'Plugin type'
    key:
      type: string
      label: 'Plugin query key'
    message_type:
      type: string
      label: 'Prompt message type'
    force:
      type: boolean
      label: 'Prompt mesage with force mode'
    message:
      type: text
      label: 'Prompt message'
    params:
      type: mapping
      label: 'Plugin params'
